export function dashboardView(session, stats={}) {
  const role=String(session?.Role||'STUDENT').toUpperCase();
  const name=session?.FullName||'Portal user';
  const roleConfig={
    SUPER_ADMIN:{title:'Executive Control Center',subtitle:'Full portal governance, security and operational oversight.',kpis:['Total Users','Pending Approvals','Active Students','Open Issues','Attendance Today','System Health']},
    ADMIN:{title:'Administration Dashboard',subtitle:'Students, staff access, operations and reports.',kpis:['Students','Pending Approvals','Total Users','Open Issues','Attendance Today','System Health']},
    HR:{title:'HR & People Dashboard',subtitle:'Student onboarding, placement, approvals and workforce support.',kpis:['Pending Students','Active Interns','Placements','Pending Documents','Attendance Today','Total Users']},
    COORDINATOR:{title:'SIWES Coordinator Dashboard',subtitle:'Placement progress, attendance, learning and supervisor activity.',kpis:['Students','Pending Approvals','Attendance','Learning Progress','Assessments','At Risk']},
    SUPERVISOR:{title:'Supervisor Dashboard',subtitle:'Track assigned students, activities, attendance and assessments.',kpis:['Assigned Students','Present Today','Pending Logs','Open Tickets','Learning Progress','Assessments']},
    SUPPORT:{title:'Technical Support Dashboard',subtitle:'Support workload, incidents, SLA and technical learning.',kpis:['Open Tickets','Resolved Today','Escalations','SLA','Testing Activities','Learning Entries']},
    STUDENT:{title:'Student Dashboard',subtitle:'Your SIWES journey, attendance, logbook, learning and assessments.',kpis:['Attendance','Learning Progress','Logbook Entries','Open Tickets','Assessment','Days Remaining']}
  }[role]||{title:'Portal Dashboard',subtitle:'SIWES operations workspace.',kpis:['Students','Attendance','Learning Progress','Open Tickets','Assessments','Reports']};
  const values=stats.metrics||stats.kpis||{};
  return `<div class="role-dashboard"><section class="pagehead"><div><span class="eyebrow">${role}</span><h1>${roleConfig.title}</h1><p>${roleConfig.subtitle}</p></div><div class="identity-chip"><b>${name}</b><span>${session?.Email||''}</span></div></section><div class="dashboard-kpis">${roleConfig.kpis.map(k=>`<article class="card kpi"><small>${k}</small><strong>${values[k] ?? '—'}</strong><span>Live from portal records</span></article>`).join('')}</div><div class="dashboard-panels"><section class="panel"><div class="panel-title"><div><small>WORK QUEUE</small><h3>What needs attention</h3></div><button class="link-btn" data-page="notifications">View alerts →</button></div><div class="queue-grid"><button class="queue-item" data-page="students"><b>Student management</b><span>Review records, approvals and status</span></button><button class="queue-item" data-page="attendance"><b>Attendance</b><span>Check presence, late entries and verification</span></button><button class="queue-item" data-page="logs"><b>Daily logbook</b><span>Review technical activities and learning</span></button><button class="queue-item" data-page="tickets"><b>Technical support</b><span>Track issues, escalation and resolution</span></button></div></section><section class="panel"><div class="panel-title"><div><small>LEARNING</small><h3>Training tracks</h3></div><button class="link-btn" data-page="learning">Open plan →</button></div><div class="track-list"><div><b>SIWES</b><span>3 months · structured practical learning</span></div><div><b>IT</b><span>6 months · deeper industrial training and capstone</span></div><div><b>Course aligned</b><span>Programme → competency → Technical Support activity</span></div></div></section></div></div>`;
}
