// Credlock SIWES Portal — production Google Apps Script API
// Passwords are intentionally stored as plain text, per project requirement.
// Configure SUPER_ADMIN_PASSWORD in Apps Script Script Properties before first login.

const SHEET_ID='1zGxiKWpJyerrCzn1vlTXBL9SMYJaxFy-6EtYCdvCL5w';
const SUPER_ADMIN_EMAIL='josepholayemi35@gmail.com';
const SUPER_ADMIN_PASSWORD_PROPERTY='SUPER_ADMIN_PASSWORD';
const SESSION_SECONDS=21600, RESET_SECONDS=1800;
const SHEETS={USERS:'USERS',STUDENTS:'STUDENTS',ATTENDANCE:'ATTENDANCE',DAILY_LOG:'DAILY_ACTIVITY_LOG',TICKETS:'ISSUE_LOG',LEARNING:'LEARNING_PLAN',ASSESSMENTS:'SUPERVISOR_ASSESSMENT',EVALUATIONS:'MONTHLY_EVALUATION',CONFIG:'CONFIG',AUDIT:'AUDIT_LOG'};
const HEADERS={
USERS:['UserID','SIWESID','FullName','Email','Phone','Password','Role','Status','LastLogin','CreatedAt','UpdatedAt'],
STUDENTS:['StudentID','SIWESID','UserID','FullName','FirstName','MiddleName','LastName','Gender','DateOfBirth','Phone','Email','Address','Institution','MatricNumber','Programme','Department','Level','AcademicSession','Organization','Supervisor','StartDate','EndDate','Status','CreatedAt','UpdatedAt'],
ATTENDANCE:['AttendanceID','StudentID','SIWESID','Date','Day','ClockIn','ClockOut','HoursWorked','Status','Late','Location','SupervisorVerified','SupervisorRemarks','CreatedAt','UpdatedAt'],
DAILY_LOG:['ActivityID','StudentID','SIWESID','Date','Day','Week','Month','Activity','IssueRequest','ActionTaken','Outcome','Status','Escalated','EscalatedTo','WhatILearned','TestingActivity','LearningEntry','ActivityCount','ResolvedCount','EscalatedCount','TestingCount','VerificationStatus','SupervisorRemarks','CreatedAt','UpdatedAt'],
TICKETS:['IssueID','StudentID','SIWESID','Date','Category','Description','Priority','ActionTaken','Outcome','Status','Escalated','EscalatedTo','Resolution','LearningOutcome','SupervisorRemarks','CreatedAt','UpdatedAt'],
LEARNING:['LearningPlanID','Programme','Session','Week','Topic','LearningObjective','ExpectedSkill','Activity','AssessmentCriteria','Status'],
ASSESSMENTS:['AssessmentID','StudentID','SIWESID','SupervisorID','Month','TechnicalKnowledge','ProblemSolving','Documentation','Responsiveness','Escalation','Communication','Teamwork','LearningInitiative','Reliability','TotalScore','AverageScore','Comments','SubmittedAt'],
EVALUATIONS:['EvaluationID','StudentID','SIWESID','Month','ActivityTarget','ActivitiesActual','ActivityAchievement','IssueCompletion','TestingTarget','TestingActual','TestingAchievement','LearningTarget','LearningActual','LearningAchievement','AttendanceParticipation','OverallKPI','PerformanceGrade','FinalAssessment','CreatedAt'],
CONFIG:['Setting','Value','Description','UpdatedAt'],AUDIT:['AuditID','UserID','Role','Action','Module','RecordID','Description','Timestamp']};

function doGet(e){
  try{
    if(e&&e.parameter&&e.parameter.api==='1') return json_({success:true,service:'Credlock SIWES API',version:'3.1.0',status:'ONLINE',timestamp:new Date().toISOString(),sheetId:SHEET_ID});
    if(typeof initializePortalSchema_==='function') initializePortalSchema_();
    if(typeof initializeCyberSecurityTrack_==='function') initializeCyberSecurityTrack_();
    return HtmlService.createHtmlOutput('<!doctype html><html><head><base target="_top"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Credlock SIWES Portal</title><style>html,body,iframe{margin:0;width:100%;height:100%;border:0;overflow:hidden}body{background:#f5f7fb}</style></head><body><iframe src="https://joseph-cyber-max.github.io/credlock-siwes-portal/" title="Credlock SIWES Portal" allow="camera;geolocation"></iframe></body></html>').setTitle('Credlock SIWES Portal');
  }catch(x){return HtmlService.createHtmlOutput('<h3>Credlock SIWES Portal</h3><p>Portal initialization failed: '+String(x.message||x).replace(/[<>]/g,'')+'</p><p>Use <b>?api=1</b> to check the backend API.</p>');}
}
function doPost(e){try{ensureSchema_();const b=JSON.parse((e&&e.postData&&e.postData.contents)||'{}'),a=String(b.action||'').trim(),p=b.payload||{};let r;switch(a){case'login':r=login_(p.email||p.key||p.siwesId,p.password||p.pin);break;case'logout':r=logout_(p.token);break;case'session':r=session_(p.token);break;case'register':r=register_(p);break;case'requestPasswordReset':r=requestPasswordReset_(p.email);break;case'resetPassword':r=resetPassword_(p.token,p.newPassword||p.password);break;case'changePassword':r=changePassword_(p.token,p.oldPassword,p.newPassword);break;case'dashboard':r=dashboard_(p.token);break;case'students':r=students_(p.token);break;case'attendance':r=rowsApi_(p.token,SHEETS.ATTENDANCE);break;case'dailyLogs':r=rowsApi_(p.token,SHEETS.DAILY_LOG);break;case'tickets':r=rowsApi_(p.token,SHEETS.TICKETS);break;case'learningPlan':r=rowsApi_(p.token,SHEETS.LEARNING);break;case'assessments':r=rowsApi_(p.token,SHEETS.ASSESSMENTS);break;case'finalAssessment':r=rowsApi_(p.token,SHEETS.EVALUATIONS);break;case'config':r=config_(p.token);break;case'lookups':r=lookups_(p.token);break;case'saveStudent':r=saveStudent_(p.token,p);break;case'saveDailyLog':r=saveRecord_(p.token,SHEETS.DAILY_LOG,p,'DAILY_LOG');break;case'saveTicket':r=saveRecord_(p.token,SHEETS.TICKETS,p,'TICKET');break;case'saveAttendance':r=saveRecord_(p.token,SHEETS.ATTENDANCE,p,'ATTENDANCE');break;default:r=err_('Unknown action: '+a,'UNKNOWN_ACTION');}return json_(r);}catch(x){return json_(err_(x.message||String(x),'SERVER_ERROR'));}}

function login_(key,password){key=String(key||'').trim().toLowerCase();password=String(password||'');if(!key||!password)return err_('Email/SIWES ID and password are required.','VALIDATION');ensureSuperAdmin_();const u=rows_(SHEETS.USERS).find(x=>String(x.Email||'').trim().toLowerCase()===key||String(x.SIWESID||'').trim().toLowerCase()===key);if(!u)return err_('Invalid credentials.','AUTH_FAILED');if(String(u.Status||'').toUpperCase()!=='ACTIVE')return err_('Your account is not active.','ACCOUNT_INACTIVE');if(String(u.Password||'')!==password)return err_('Invalid credentials.','AUTH_FAILED');const token=Utilities.getUuid(),safe={UserID:u.UserID,SIWESID:u.SIWESID,FullName:u.FullName,Email:u.Email,Phone:u.Phone,Role:u.Role,Status:u.Status};CacheService.getScriptCache().put('SESSION_'+token,JSON.stringify(safe),SESSION_SECONDS);updateById_(SHEETS.USERS,'UserID',u.UserID,{LastLogin:new Date(),UpdatedAt:new Date()});audit_(safe,'LOGIN','AUTH','','Successful portal login');return ok_({token:token,Token:token,session:safe,user:safe,FullName:safe.FullName,Email:safe.Email,Role:safe.Role,SIWESID:safe.SIWESID},'Login successful.');}
function register_(p){const fullName=String(p.fullName||'').trim(),email=String(p.email||'').trim().toLowerCase(),password=String(p.password||''),phone=String(p.phone||'').trim();if(!fullName||!email||!password)return err_('Full name, email and password are required.','VALIDATION');if(!/^\S+@\S+\.\S+$/.test(email))return err_('Enter a valid email address.','VALIDATION');if(password.length<6)return err_('Password must be at least 6 characters.','VALIDATION');if(rows_(SHEETS.USERS).some(u=>String(u.Email||'').trim().toLowerCase()===email))return err_('An account with this email already exists.','DUPLICATE');const id='USR-'+Utilities.getUuid().slice(0,8).toUpperCase(),sid='SIWES-'+new Date().getFullYear()+'-'+String(nextNumber_()).padStart(4,'0'),now=new Date();append_(SHEETS.USERS,{UserID:id,SIWESID:sid,FullName:fullName,Email:email,Phone:phone,Password:password,Role:'STUDENT',Status:'PENDING',CreatedAt:now,UpdatedAt:now});append_(SHEETS.STUDENTS,{StudentID:'STD-'+Utilities.getUuid().slice(0,8).toUpperCase(),SIWESID:sid,UserID:id,FullName:fullName,FirstName:p.firstName||fullName.split(' ')[0],LastName:p.lastName||'',Phone:phone,Email:email,Institution:p.institution||'',MatricNumber:p.matricNumber||'',Programme:p.programme||'',Department:p.department||'',Level:p.level||'',AcademicSession:p.academicSession||'',Organization:p.organization||'',Status:'PENDING',CreatedAt:now,UpdatedAt:now});return ok_({SIWESID:sid,status:'PENDING'},'Registration submitted successfully. Your account will be activated after verification.');}
function requestPasswordReset_(email){email=String(email||'').trim().toLowerCase();if(!email)return err_('Email is required.','VALIDATION');const u=rows_(SHEETS.USERS).find(x=>String(x.Email||'').trim().toLowerCase()===email&&String(x.Status||'').toUpperCase()!=='DELETED'),message='If an account exists for this email, a reset token has been prepared.';if(!u)return ok_({},message);const token=Utilities.getUuid()+Utilities.getUuid().replace(/-/g,'');CacheService.getScriptCache().put('PWDRESET_'+token,JSON.stringify({UserID:u.UserID,Email:u.Email}),RESET_SECONDS);return ok_({resetToken:token,expiresIn:RESET_SECONDS},message);}
function resetPassword_(token,newPassword){newPassword=String(newPassword||'');const raw=CacheService.getScriptCache().get('PWDRESET_'+String(token||''));if(!raw)return err_('Reset token is invalid or expired.','RESET_INVALID');if(newPassword.length<6)return err_('Reset password must be at least 6 characters.','VALIDATION');const u=JSON.parse(raw);updateById_(SHEETS.USERS,'UserID',u.UserID,{Password:newPassword,UpdatedAt:new Date()});CacheService.getScriptCache().remove('PWDRESET_'+token);return ok_({},'Password reset successfully.');}
function changePassword_(token,oldPassword,newPassword){const u=require_(token);const row=rows_(SHEETS.USERS).find(x=>x.UserID===u.UserID);if(!row||String(row.Password||'')!==String(oldPassword||''))return err_('Current password is incorrect.','AUTH_FAILED');if(String(newPassword||'').length<6)return err_('New password must be at least 6 characters.','VALIDATION');updateById_(SHEETS.USERS,'UserID',u.UserID,{Password:String(newPassword),UpdatedAt:new Date()});return ok_({},'Password changed successfully.');}
function logout_(token){if(token)CacheService.getScriptCache().remove('SESSION_'+token);return ok_({},'Signed out.');}
function session_(token){return ok_(require_(token),'Session valid.');}
function require_(token,roles){const raw=CacheService.getScriptCache().get('SESSION_'+String(token||''));if(!raw)throw Error('Session expired. Please sign in again.');const u=JSON.parse(raw);if(roles&&roles.length&&roles.indexOf(String(u.Role).toUpperCase())<0)throw Error('You do not have permission for this action.');return u;}
function rowsApi_(token,sheet){require_(token);return ok_(rows_(sheet));}
function students_(token){const u=require_(token,['ADMIN','SUPER_ADMIN','COORDINATOR','SUPERVISOR','STUDENT']);let r=rows_(SHEETS.STUDENTS).filter(x=>String(x.Status||'').toUpperCase()!=='DELETED');if(String(u.Role).toUpperCase()==='STUDENT')r=r.filter(x=>x.UserID===u.UserID);return ok_(r);}
function dashboard_(token){const u=require_(token),s=rows_(SHEETS.STUDENTS).find(x=>x.UserID===u.UserID)||rows_(SHEETS.STUDENTS)[0],logs=rows_(SHEETS.DAILY_LOG),att=rows_(SHEETS.ATTENDANCE),tickets=rows_(SHEETS.TICKETS),mine=String(u.Role).toUpperCase()==='STUDENT',myLogs=mine?logs.filter(x=>x.StudentID===s?.StudentID||x.SIWESID===u.SIWESID):logs,myAtt=mine?att.filter(x=>x.StudentID===s?.StudentID||x.SIWESID===u.SIWESID):att,present=myAtt.filter(x=>String(x.Status||'').toUpperCase()==='PRESENT').length;return ok_({intern:s?.FullName||u.FullName,department:s?.Department||'Technical Support',company:s?.Organization||'Credlock Africa',supervisor:s?.Supervisor||'Not assigned',attendance:myAtt.length?Math.round(present/myAtt.length*100):0,completion:Math.min(100,myLogs.length*5),sla:tickets.length?Math.round(tickets.filter(x=>['CLOSED','RESOLVED'].includes(String(x.Status||'').toUpperCase())).length/tickets.length*100):0,issues:tickets.length,trainingHours:myAtt.reduce((n,x)=>n+(Number(x.HoursWorked)||0),0),finalScore:0,user:u},'Dashboard loaded.');}
function config_(token){require_(token);const o={};rows_(SHEETS.CONFIG).forEach(r=>o[r.Setting]=r.Value);o.SpreadsheetId=SHEET_ID;o.SuperAdminEmail=SUPER_ADMIN_EMAIL;return ok_(o);}
function lookups_(token){require_(token);return ok_({institutions:unique_(SHEETS.STUDENTS,'Institution'),programmes:unique_(SHEETS.STUDENTS,'Programme'),departments:unique_(SHEETS.STUDENTS,'Department'),levels:unique_(SHEETS.STUDENTS,'Level'),organizations:unique_(SHEETS.STUDENTS,'Organization')});}
function saveStudent_(token,p){const u=require_(token,['ADMIN','SUPER_ADMIN']);const id=p.StudentID||'STD-'+Utilities.getUuid().slice(0,8).toUpperCase(),sid=p.SIWESID||'SIWES-'+new Date().getFullYear()+'-'+String(nextNumber_()).padStart(4,'0'),d=Object.assign({},p,{StudentID:id,SIWESID:sid,Status:p.Status||'ACTIVE',UpdatedAt:new Date(),CreatedAt:p.CreatedAt||new Date()});if(rows_(SHEETS.STUDENTS).some(x=>x.StudentID===id))updateById_(SHEETS.STUDENTS,'StudentID',id,d);else append_(SHEETS.STUDENTS,d);audit_(u,'SAVE','STUDENTS',id,'Student record saved');return ok_(d,'Student saved.');}
function saveRecord_(token,sheet,p,module){const u=require_(token,['ADMIN','SUPER_ADMIN','COORDINATOR','SUPERVISOR','STUDENT']),d=Object.assign({},p),key=sheet===SHEETS.DAILY_LOG?'ActivityID':sheet===SHEETS.TICKETS?'IssueID':'AttendanceID';d[key]=d[key]||module+'-'+Utilities.getUuid().slice(0,8).toUpperCase();d.CreatedAt=d.CreatedAt||new Date();d.UpdatedAt=new Date();append_(sheet,d);audit_(u,'CREATE',module,d[key],'Record created');return ok_(d,'Record saved.');}
function ensureSchema_(){const ss=SpreadsheetApp.openById(SHEET_ID);if(typeof initializePortalSchema_==='function')initializePortalSchema_();if(typeof initializeCyberSecurityTrack_==='function')initializeCyberSecurityTrack_();Object.keys(HEADERS).forEach(k=>{let sh=ss.getSheetByName(SHEETS[k]);if(!sh)sh=ss.insertSheet(SHEETS[k]);if(sh.getLastRow()===0)sh.getRange(1,1,1,HEADERS[k].length).setValues([HEADERS[k]]);});ensureSuperAdmin_();ensureLearning_();}
function ensureSuperAdmin_(){const users=rows_(SHEETS.USERS);if(users.some(x=>String(x.Email||'').toLowerCase()===SUPER_ADMIN_EMAIL))return;const password=PropertiesService.getScriptProperties().getProperty(SUPER_ADMIN_PASSWORD_PROPERTY);if(!password)return;const now=new Date();append_(SHEETS.USERS,{UserID:'USR-SUPERADMIN',SIWESID:'SUPERADMIN',FullName:'Super Admin',Email:SUPER_ADMIN_EMAIL,Phone:'',Password:password,Role:'SUPER_ADMIN',Status:'ACTIVE',CreatedAt:now,UpdatedAt:now});}
function ensureLearning_(){const sh=sheet_(SHEETS.LEARNING);if(sh.getLastRow()>1)return;const areas=['Basic Computer & System Operations','Technical Support Basics','Ticket & Customer Support','Device & Enrollment Support','Credlock Platform & Troubleshooting','Reporting & Documentation'],r=[];for(let i=1;i<=12;i++)r.push(['LP-'+String(i).padStart(2,'0'),'Computer Science','2026',i,areas[Math.min(i-1,5)],'Build practical SIWES competency.','Demonstrate the weekly skill.','Guided technical support activity.','Supervisor review and evidence.','ACTIVE']);sh.getRange(2,1,r.length,HEADERS.LEARNING.length).setValues(r);}
function sheet_(name){const sh=SpreadsheetApp.openById(SHEET_ID).getSheetByName(name);if(!sh)throw Error('Missing sheet: '+name);return sh;}
function rows_(name){const sh=sheet_(name),v=sh.getDataRange().getValues();if(v.length<2)return[];const h=v[0].map(String);return v.slice(1).filter(r=>r.some(x=>x!==''&&x!==null)).map(r=>{const o={};h.forEach((k,i)=>{if(k)o[k]=r[i] instanceof Date?r[i].toISOString():r[i]});return o;});}
function append_(name,obj){const sh=sheet_(name),h=HEADERS[Object.keys(SHEETS).find(k=>SHEETS[k]===name)]||sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];sh.appendRow(h.map(k=>obj[k]===undefined?'':obj[k]));}
function updateById_(name,idField,id,data){const sh=sheet_(name),v=sh.getDataRange().getValues();if(v.length<2)return false;const h=v[0].map(String),idx=h.indexOf(idField);if(idx<0)throw Error('Missing id field: '+idField);for(let i=1;i<v.length;i++){if(String(v[i][idx])===String(id)){Object.keys(data).forEach(k=>{const c=h.indexOf(k);if(c>=0)sh.getRange(i+1,c+1).setValue(data[k]);});return true;}}return false;}
function unique_(name,field){const a=rows_(name).map(x=>String(x[field]||'').trim()).filter(Boolean);return [...new Set(a)].sort();}
function nextNumber_(){return rows_(SHEETS.USERS).length+1;}
function ok_(data,message){return{success:true,data:data||{},message:message||'OK'};}
function err_(message,code){return{success:false,error:true,code:code||'ERROR',message:String(message||'Error')};}
function audit_(u,action,module,id,description){try{append_(SHEETS.AUDIT,{AuditID:'AUD-'+Utilities.getUuid().slice(0,8).toUpperCase(),UserID:u?.UserID||'',Role:u?.Role||'',Action:action,Module:module,RecordID:id||'',Description:description||'',Timestamp:new Date()});}catch(_){}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
