// Course-of-study mapping for Technical Support learning customization.
const COURSE_DOMAIN_RULES_=[
  {patterns:['computer science','software engineering','software development'],domain:'Application Support & Software QA',focus:'Programming support, application troubleshooting, testing, version control and documentation'},
  {patterns:['information technology','information systems','business information technology','information management'],domain:'IT Infrastructure & Help Desk',focus:'Help desk, networking, endpoints, accounts, systems support and service operations'},
  {patterns:['cyber security','cybersecurity','information security'],domain:'Cyber Security Operations',focus:'Security awareness, access control, incident response, monitoring and secure support'},
  {patterns:['computer engineering','electrical engineering','electronic engineering','electronics'],domain:'Device & Network Support',focus:'Device diagnostics, hardware fundamentals, networking, connectivity and MDM'},
  {patterns:['data science','data analytics','statistics'],domain:'Data & Technical Analytics',focus:'Data quality, reporting, dashboards, analytics and technical investigation'},
  {patterns:['telecommunication','telecommunications','communication engineering'],domain:'Networks & Connectivity',focus:'Connectivity, network diagnostics, infrastructure support and service monitoring'},
  {patterns:['accounting','business administration','management','economics'],domain:'Business Systems Support',focus:'Business applications, user support, reporting, workflow and documentation'}
];
function courseDomain_(programme,department){const text=(String(programme||'')+' '+String(department||'')).toLowerCase();for(let i=0;i<COURSE_DOMAIN_RULES_.length;i++){const r=COURSE_DOMAIN_RULES_[i];if(r.patterns.some(function(p){return text.indexOf(p)>=0;}))return r;}return {domain:'Core Technical Support',focus:'Customer support, endpoint support, troubleshooting, documentation, escalation and service quality'};}
function applyCourseLearningDomain_(student){const r=courseDomain_(student.Programme,student.Department);return {CourseDomain:r.domain,CourseFocus:r.focus};}
function updateCourseDomains_(){const sh=SpreadsheetApp.openById(SHEET_ID).getSheetByName('STUDENTS');if(!sh||sh.getLastRow()<2)return;let h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);['CourseDomain','CourseFocus'].forEach(function(k){if(h.indexOf(k)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(k);h.push(k);}});const idx={};h.forEach(function(k,i){idx[k]=i;});const rows=sh.getRange(2,1,sh.getLastRow()-1,sh.getLastColumn()).getValues();rows.forEach(function(r){const x=applyCourseLearningDomain_({Programme:r[idx.Programme]||'',Department:r[idx.Department]||''});r[idx.CourseDomain]=x.CourseDomain;r[idx.CourseFocus]=x.CourseFocus;});sh.getRange(2,1,rows.length,sh.getLastColumn()).setValues(rows);}
