// HR operations: review student registrations, approve/reject access, assign placements and manage HR lifecycle.
const HR_STATUSES_=['PENDING','ACTIVE','INACTIVE','SUSPENDED','DELETED','REJECTED'];

function hrDashboard_(token){
  const u=require_(token); if(!hasPermission_(u,'students.view') && !['HR','ADMIN','SUPER_ADMIN'].includes(String(u.Role).toUpperCase())) throw Error('HR permission required.');
  const students=rows_(SHEETS.STUDENTS).filter(x=>String(x.Status||'').toUpperCase()!=='DELETED');
  const users=rows_(SHEETS.USERS).filter(x=>String(x.Status||'').toUpperCase()!=='DELETED');
  const pending=students.filter(x=>String(x.Status||'').toUpperCase()==='PENDING').length;
  const active=students.filter(x=>String(x.Status||'').toUpperCase()==='ACTIVE').length;
  const withOrg=students.filter(x=>String(x.Organization||'').trim()).length;
  const attendance=rows_(SHEETS.ATTENDANCE);
  const today=new Date(); const day=Utilities.formatDate(today,Session.getScriptTimeZone(),'yyyy-MM-dd');
  const attendanceToday=attendance.filter(x=>String(x.Date||'').indexOf(day)>=0 && ['PRESENT','LATE'].includes(String(x.Status||'').toUpperCase())).length;
  return ok_({metrics:{pendingStudents:pending,activeStudents:active,placements:withOrg,pendingDocuments:0,attendanceToday:attendanceToday,totalUsers:users.length},students:students.slice(-100).reverse()},'HR dashboard loaded.');
}

function hrReviewStudents_(token){const u=require_(token);requireHr_(u);return ok_(rows_(SHEETS.STUDENTS).filter(x=>String(x.Status||'').toUpperCase()!=='DELETED'),'Student review queue loaded.');}

function hrApproveStudent_(token,p){const actor=require_(token);requireHr_(actor);const id=String(p.StudentID||'').trim();if(!id)return err_('StudentID is required.','VALIDATION');const student=rows_(SHEETS.STUDENTS).find(x=>String(x.StudentID)===id);if(!student)return err_('Student not found.','NOT_FOUND');const now=new Date();updateById_(SHEETS.STUDENTS,'StudentID',id,{Status:'ACTIVE',UpdatedAt:now});if(student.UserID)updateById_(SHEETS.USERS,'UserID',student.UserID,{Status:'ACTIVE',Role:'STUDENT',UpdatedAt:now});ensureStudentLearningTrack_(student);notifyUser_(student.UserID,'Portal access approved','Your SIWES/IT portal account has been approved. You can now sign in.','APPROVAL');audit_(actor,'APPROVE_STUDENT','STUDENTS',id,'Student account approved by HR');return ok_({StudentID:id,Status:'ACTIVE'},'Student approved and portal access activated.');}

function hrRejectStudent_(token,p){const actor=require_(token);requireHr_(actor);const id=String(p.StudentID||'').trim(),reason=String(p.Reason||p.reason||'Verification requirements not satisfied.').trim();const student=rows_(SHEETS.STUDENTS).find(x=>String(x.StudentID)===id);if(!student)return err_('Student not found.','NOT_FOUND');const now=new Date();updateById_(SHEETS.STUDENTS,'StudentID',id,{Status:'REJECTED',UpdatedAt:now});if(student.UserID)updateById_(SHEETS.USERS,'UserID',student.UserID,{Status:'REJECTED',UpdatedAt:now});notifyUser_(student.UserID,'Portal registration update',reason,'REGISTRATION');audit_(actor,'REJECT_STUDENT','STUDENTS',id,'Student rejected: '+reason);return ok_({StudentID:id,Status:'REJECTED'},'Student registration rejected.');}

function hrAssignPlacement_(token,p){const actor=require_(token);requireHr_(actor);const id=String(p.StudentID||'').trim();const student=rows_(SHEETS.STUDENTS).find(x=>String(x.StudentID)===id);if(!student)return err_('Student not found.','NOT_FOUND');const update={Organization:String(p.Organization||'').trim(),Supervisor:String(p.Supervisor||'').trim(),StartDate:p.StartDate||'',EndDate:p.EndDate||'',UpdatedAt:new Date()};updateById_(SHEETS.STUDENTS,'StudentID',id,update);notifyUser_(student.UserID,'Placement updated','Your SIWES/IT placement information has been updated.','PLACEMENT');audit_(actor,'ASSIGN_PLACEMENT','STUDENTS',id,'Placement assigned/updated');return ok_(Object.assign({StudentID:id},update),'Placement updated.');}

function hrResetUserPassword_(token,p){const actor=require_(token);requireSuperAdmin_(actor);const id=String(p.UserID||'').trim(),newPassword=String(p.NewPassword||p.newPassword||'');if(!id||newPassword.length<6)return err_('UserID and a password of at least 6 characters are required.','VALIDATION');const target=rows_(SHEETS.USERS).find(x=>String(x.UserID)===id);if(!target)return err_('User not found.','NOT_FOUND');updateById_(SHEETS.USERS,'UserID',id,{Password:newPassword,UpdatedAt:new Date()});audit_(actor,'RESET_PASSWORD','USERS',id,'Password reset by Super Admin');return ok_({UserID:id},'Password reset successfully.');}

function requireHr_(u){const r=String(u.Role||'').toUpperCase();if(String(u.Email||'').toLowerCase()===SUPER_ADMIN_EMAIL)return;if(!['HR','ADMIN','COORDINATOR','SUPER_ADMIN'].includes(r))throw Error('HR/administration permission required.');}
function ensureStudentLearningTrack_(student){try{const ss=SpreadsheetApp.openById(SHEET_ID),sh=ss.getSheetByName('STUDENTS');if(!sh)return;const headers=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);['TrainingType','LearningTrack','CourseDomain'].forEach(function(k){if(headers.indexOf(k)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(k);headers.push(k);}});const h2=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);const row=rows_(SHEETS.STUDENTS).find(x=>String(x.StudentID)===String(student.StudentID));const values={TrainingType:String(row.TrainingType||student.TrainingType||'SIWES').toUpperCase()==='IT'?'IT':'SIWES',LearningTrack:'',CourseDomain:(row.Programme||student.Programme||'')+' / '+(row.Department||student.Department||'')+' → Technical Support'};values.LearningTrack=values.TrainingType==='IT'?'IT — 6 Months · Technical Support':'SIWES — 3 Months · Technical Support';updateById_(SHEETS.STUDENTS,'StudentID',student.StudentID,values);}catch(e){}}
function notifyUser_(userId,title,message,type){if(!userId)return;try{ensureSchema_();append_(SHEETS.NOTIFICATIONS,{NotificationID:'NOTIF-'+Utilities.getUuid().slice(0,8).toUpperCase(),UserID:userId,Title:title,Message:message,Type:type||'INFO',Read:false,CreatedAt:new Date()});}catch(e){}}
function dispatchHr_(action,token,p){switch(action){case 'hrDashboard':return hrDashboard_(token);case 'hrReviewStudents':return hrReviewStudents_(token);case 'hrApproveStudent':return hrApproveStudent_(token,p);case 'hrRejectStudent':return hrRejectStudent_(token,p);case 'hrAssignPlacement':return hrAssignPlacement_(token,p);case 'hrResetUserPassword':return hrResetUserPassword_(token,p);default:return null;}}
