import {useEffect,useMemo,useState} from 'react';
import {LayoutDashboard,Users,Clock3,BookOpenCheck,Ticket,GraduationCap,ClipboardCheck,FileText,Settings,LogOut,Menu,X,RefreshCw,Search,ShieldCheck,ExternalLink,ChevronRight} from 'lucide-react';
import Registration from './pages/auth/Registration';
import PasswordReset from './pages/auth/PasswordReset';
import {APPS_SCRIPT_URL as API,SHEET_URL as SHEET,GITHUB_URL as GITHUB,PAGES_URL as PAGES} from './config';
import './pages/auth/Auth.css';
const modules=[['dashboard','Dashboard',LayoutDashboard],['students','Students',Users],['attendance','Attendance',Clock3],['logbook','Daily Logbook',BookOpenCheck],['tickets','Ticket Log',Ticket],['learning','Learning Plan',GraduationCap],['assessments','Assessments',ClipboardCheck],['reports','Reports',FileText],['settings','Settings',Settings]];
async function request(action,payload={}){const token=(()=>{try{const u=JSON.parse(sessionStorage.getItem('credlock_user')||'{}');return u.token||u.Token||''}catch{return ''}})();const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload:{...payload,token}})});const j=await r.json();if(!j.success)throw Error(j.message||'Request failed');return j.data??j;}
async function requestPublic(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.success)throw Error(j.message||'Request failed');return j.data??j;}
const fmt=v=>v==null||v===''?'—':String(v);
function user(){try{return JSON.parse(sessionStorage.getItem('credlock_user')||'null')}catch{return null}}
function Login(){const[login,setLogin]=useState({email:'',password:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');async function go(e){e.preventDefault();setBusy(true);setError('');try{const email=login.email.trim(),pin=login.password;const d=await requestPublic('login',{email,password:pin,pin,key:email,siwesId:email});const session=d?.user?{...d.user,...d,token:d.token||d.Token}:d;sessionStorage.setItem('credlock_user',JSON.stringify(session));location.hash='#/admin';location.reload()}catch(x){setError(x.message||'Unable to sign in.')}finally{setBusy(false)}}return <div className="login"><div className="login-left"><div className="brand"><span>C</span><div><b>Credlock</b><small>SIWES Portal</small></div></div><div className="hero"><span className="pill"><ShieldCheck size={15}/> Secure academic operations</span><h1>Manage SIWES<br/><i>smarter.</i></h1><p>Students, placements, attendance, daily activities, support tickets, learning plans and assessments in one connected workspace.</p></div><footer>Credlock Africa · SIWES Management</footer></div><div className="login-right"><form onSubmit={go} className="login-card"><span className="eyebrow">PORTAL ACCESS</span><h2>Welcome back</h2><p>Sign in with your authorized portal account.</p><label className="field-label">Email<input type="email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} required placeholder="you@example.com" autoComplete="username"/></label><label className="field-label">Access PIN<input type="password" inputMode="numeric" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} required placeholder="Enter your access PIN" autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Signing in…':'Sign in'} <ChevronRight size={17}/></button><div className="auth-links"><a href="#/register">Create student account</a><a href="#/reset-password">Forgot PIN?</a></div><div className="secure"><ShieldCheck size={15}/> Google Apps Script backend</div></form></div></div>}
function Portal({onLogout}){const[page,setPage]=useState('dashboard'),[open,setOpen]=useState(true),[data,setData]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),u=user();const load=async(p=page)=>{setBusy(true);setError('');try{const map={dashboard:'dashboard',students:'students',attendance:'attendance',logbook:'dailyLogs',tickets:'tickets',learning:'learningPlan',assessments:'assessments',reports:'dashboard',settings:'config'};setData(await request(map[p]||'dashboard'))}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load(page)},[page]);const active=modules.find(x=>x[0]===page);return <div className="shell"><aside className={open?'sidebar':'sidebar collapsed'}><div className="sidebrand"><span>C</span>{open&&<div><b>Credlock</b><small>SIWES Portal</small></div>}<button onClick={()=>setOpen(!open)} className="icon" aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div>{open&&<div className="section-title">WORKSPACE</div>}<nav>{modules.map(([id,label,I])=><button key={id} onClick={()=>setPage(id)} className={page===id?'nav active':'nav'} title={label}><I size={18}/>{open&&<span>{label}</span>}</button>)}</nav><div className="sidebottom"><button className="nav" onClick={()=>setPage('settings')}><Settings size={18}/>{open&&<span>Settings</span>}</button><button className="profile" onClick={onLogout}><span>{(u?.FullName||u?.name||'SA').slice(0,2).toUpperCase()}</span>{open&&<div><b>{fmt(u?.FullName||u?.name)}</b><small>{fmt(u?.Role||u?.role)}</small></div>}<LogOut size={16}/></button></div></aside><main className="main"><header><div><span>SIWES Portal</span><strong> / {active?.[1]}</strong></div><div className="header-right"><span className="live"><i/> Live</span><button className="icon" onClick={()=>load()} aria-label="Refresh"><RefreshCw size={18}/></button><span className="top-user">{fmt(u?.FullName||u?.name)}</span></div></header><section className="content">{error&&<div className="error banner">{error}<button onClick={()=>load()}>Retry</button></div>}{page==='dashboard'?<Dashboard data={data} busy={busy}/>:page==='students'?<Students rows={data||[]} onRefresh={load}/>:page==='learning'?<Learning rows={data||[]}/>:page==='reports'?<Reports/>:page==='settings'?<SettingsPage data={data}/>:<DataPage title={active?.[1]||'Records'} rows={data||[]} />}</section></main></div>}
function Dashboard({data,busy}){const cards=[['Attendance',data.attendance,'%'],['Completion',data.completion,'%'],['SLA Compliance',data.sla,'%'],['Issues Assisted',data.issues,''],['Training Hours',data.trainingHours,'h'],['Final Score',data.finalScore,'%']];return <><PageHead title="SIWES Command Center" sub="Live operational overview from Google Sheets."/><div className="identity"><div><small>INTERN</small><b>{fmt(data.intern)}</b></div><div><small>DEPARTMENT</small><b>{fmt(data.department)}</b></div><div><small>ORGANIZATION</small><b>{fmt(data.company)}</b></div><div><small>SUPERVISOR</small><b>{fmt(data.supervisor)}</b></div></div><div className="grid">{cards.map(([a,b,c])=><div className="card" key={a}><small>{a}</small><strong>{busy?'—':`${fmt(b)}${b==null?'':c}`}</strong><span>Current record</span></div>)}</div><div className="panel"><div className="panelhead"><div><b>Connected data source</b><p>Authoritative SIWES records are served by the Google Apps Script API.</p></div><a href={SHEET} target="_blank" rel="noreferrer">Open Google Sheet <ExternalLink size={15}/></a></div></div></>}
function Students({rows,onRefresh}){const[q,setQ]=useState('');const list=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);return <><PageHead title="Students" sub="Manage SIWES student records and placements." action="Refresh" onAction={onRefresh}/><div className="toolbar"><Search size={17}/><input placeholder="Search students…" value={q} onChange={e=>setQ(e.target.value)}/></div><DataTable rows={list} keys={['SIWESID','FullName','Institution','Programme','Level','Status','Supervisor']}/></>}
function Learning({rows}){return <><PageHead title="12-Week Learning Plan" sub="Structured training areas and expected outcomes."/><div className="plan-grid">{rows.map((r,i)=><article className="plan" key={i}><span>WEEK {fmt(r.Week||r.week)}</span><h3>{fmt(r.Topic||r.topic||r.Area)}</h3><p>{fmt(r.Activity||r.activities||r.LearningObjective)}</p><strong>Outcome</strong><p>{fmt(r.ExpectedSkill||r.competency||r.LearningObjective)}</p></article>)}</div></>}
function Reports(){return <><PageHead title="Reports" sub="Operational reporting and source-data access."/><div className="report-grid"><div className="panel"><h3>SIWES reporting workbook</h3><p>Attendance, completion, support activity and assessment records are available from the connected workbook.</p><a href={SHEET} target="_blank" rel="noreferrer" className="primary link">Open Google Sheet</a></div><div className="panel"><h3>Backend</h3><p>Google Apps Script is the live API layer.</p><a href={API} target="_blank" rel="noreferrer" className="live"><i/> API status</a></div></div></>}
function SettingsPage({data}){return <><PageHead title="Settings" sub="Portal configuration and administration resources."/><div className="settings"><div><small>DATA SOURCE</small><b>Google Sheets</b></div><div><small>API</small><a href={API} target="_blank" rel="noreferrer">Open Apps Script API <ExternalLink size={15}/></a></div><div><small>SPREADSHEET</small><a href={SHEET} target="_blank" rel="noreferrer">Open connected sheet <ExternalLink size={15}/></a></div><div><small>SUPER ADMIN</small><b>{fmt(data?.SuperAdminEmail)}</b></div><div><small>PORTAL SOURCE</small><a href={GITHUB} target="_blank" rel="noreferrer">Open GitHub repository <ExternalLink size={15}/></a></div><div><small>LIVE PORTAL</small><a href={PAGES} target="_blank" rel="noreferrer">Open GitHub Pages <ExternalLink size={15}/></a></div></div></>}
function PageHead({title,sub,action,onAction}){return <div className="pagehead"><div><span className="eyebrow">CREDLOCK SIWES</span><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="primary small" onClick={onAction}><RefreshCw size={16}/>{action}</button>}</div>}
function DataPage({title,rows}){const keys=rows.length?Object.keys(rows[0]).filter(k=>!['Password','PasswordHash','PasswordSalt'].includes(k)).slice(0,8):['Date','Status','Description'];return <><PageHead title={title} sub="Live records from the SIWES workbook."/><DataTable rows={rows} keys={keys}/></>}
function DataTable({rows,keys}){return <div className="tablewrap"><table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{fmt(r[k])}</td>)}</tr>):<tr><td colSpan={keys.length} className="empty">No records returned.</td></tr>}</tbody></table></div>}
function App(){const[u,setU]=useState(user());const path=location.hash.replace(/^#/, '')||'/login';if(path==='/register')return <Registration/>;if(path==='/reset-password')return <PasswordReset/>;if(!u)return <Login/>;return <Portal onLogout={()=>{sessionStorage.removeItem('credlock_user');setU(null);location.hash='#/login';location.reload()}}/>}
export default App;
