import {useEffect,useMemo,useState} from "react";
import {LayoutDashboard,Users,Clock3,BookOpenCheck,Ticket,GraduationCap,ClipboardCheck,FileText,Settings,LogOut,Menu,X,RefreshCw,Plus,Search,ShieldCheck,ExternalLink} from "lucide-react";

const API="https://script.google.com/macros/s/AKfycbyTj3mbqgJA9ySkyr1gDUxS5tYKQs_r5hbMG53ol36pjjSkXBEUxjlG226woRADwUR-qg/exec";
const SHEET="https://docs.google.com/spreadsheets/d/1zGxiKWpJyerrCzn1vlTXBL9SMYJaxFy-6EtYCdvCL5w/edit";
const modules=[
 ["dashboard","Dashboard",LayoutDashboard],["students","Students",Users],["attendance","Attendance",Clock3],["logbook","Daily Logbook",BookOpenCheck],["tickets","Ticket Log",Ticket],["learning","Learning Plan",GraduationCap],["assessments","Assessments",ClipboardCheck],["reports","Reports",FileText],["settings","Settings",Settings]
];
async function request(action,payload={}){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.success)throw Error(j.message||"Request failed");return j.data??j}
const fmt=v=>v==null||v===""?"—":String(v);
function Login({onLogin}){const[email,setEmail]=useState("");const[pin,setPin]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function go(e){e.preventDefault();setBusy(true);setError("");try{const d=await request("login",{email,pin});sessionStorage.setItem("credlock_user",JSON.stringify(d));onLogin(d)}catch(x){setError(x.message)}finally{setBusy(false)}}return <div className="login"><div className="login-left"><div className="brand"><span>C</span><div><b>Credlock</b><small>SIWES Portal</small></div></div><div className="hero"><span className="pill"><ShieldCheck size={15}/> Secure academic operations</span><h1>Manage SIWES<br/><i>smarter.</i></h1><p>Students, placements, attendance, daily activities, support tickets, learning plans and assessments in one connected workspace.</p></div><footer>Credlock Africa · SIWES Management</footer></div><div className="login-right"><form onSubmit={go} className="login-card"><span className="eyebrow">PORTAL ACCESS</span><h2>Welcome back</h2><p>Sign in with your authorized portal account.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@example.com"/></label><label>Access PIN<input type="password" value={pin} onChange={e=>setPin(e.target.value)} required placeholder="Enter PIN"/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Signing in…":"Sign in"}</button><div className="secure"><ShieldCheck size={15}/> Google Apps Script backend</div></form></div></div>}
function App(){const[user,setUser]=useState(()=>{try{return JSON.parse(sessionStorage.getItem("credlock_user")||"null")}catch{return null}});if(!user)return <Login onLogin={setUser}/>;return <Portal user={user} logout={()=>{sessionStorage.clear();setUser(null)}}/>}
function Portal({user,logout}){const[page,setPage]=useState("dashboard");const[open,setOpen]=useState(true);const[data,setData]=useState({});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const load=async(p=page)=>{setBusy(true);setError("");try{const map={dashboard:"dashboard",students:"students",attendance:"dailyLogs",logbook:"dailyLogs",tickets:"tickets",learning:"learningPlan",assessments:"finalAssessment"};setData(await request(map[p]||"dashboard"))}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load(page)},[page]);const active=modules.find(x=>x[0]===page);return <div className="shell"><aside className={open?"sidebar":"sidebar collapsed"}><div className="sidebrand"><span>C</span>{open&&<div><b>Credlock</b><small>SIWES Portal</small></div>}<button onClick={()=>setOpen(!open)} className="icon">{open?<X/>:<Menu/>}</button></div>{open&&<div className="section-title">WORKSPACE</div>}<nav>{modules.map(([id,label,I])=><button key={id} onClick={()=>setPage(id)} className={page===id?"nav active":"nav"} title={label}><I size={18}/>{open&&label}</button>)}</nav><div className="sidebottom"><button className="nav" onClick={()=>setPage("settings")}><Settings size={18}/>{open&&"Settings"}</button><button className="profile" onClick={logout}><span>{(user.FullName||user.name||"SA").slice(0,2).toUpperCase()}</span>{open&&<div><b>{fmt(user.FullName||user.name)}</b><small>{fmt(user.Role||user.role)}</small></div>}<LogOut size={16}/></button></div></aside><main className="main"><header><div><span>SIWES Portal</span><strong> / {active?.[1]}</strong></div><div className="header-right"><span className="live"><i/> Live</span><button className="icon" onClick={()=>load()}><RefreshCw size={18}/></button><span>{fmt(user.FullName||user.name)}</span></div></header><section className="content">{error&&<div className="error banner">{error}<button onClick={()=>load()}>Retry</button></div>}{page==="dashboard"?<Dashboard data={data} busy={busy}/>:page==="students"?<Students rows={data||[]} onRefresh={load}/>:page==="attendance"?<DataPage title="Attendance" rows={data||[]} keys={["Date","Timestamp","Attendance","Training Hours","Supervisor Rating"]}/>:page==="logbook"?<DataPage title="Daily Activity Log" rows={data||[]} keys={["Date","Week","Activity / Task","Skills / Knowledge Learned","Training Hours","Supervisor Rating"]}/>:page==="tickets"?<DataPage title="Ticket Log" rows={data||[]} keys={["Ticket ID","Date","Issue Type","Activity Performed","Resolution / Action","Status"]}/>:page==="learning"?<Learning rows={data||[]}/>:page==="assessments"?<DataPage title="Final Assessment" rows={data||[]} keys={["Area","Weight","Rating","Score"]}/>:page==="reports"?<Reports data={data}/>:<SettingsPage/>}</section></main></div>}
function Dashboard({data,busy}){const cards=[["Attendance",data.attendance,"%"],["Completion",data.completion,"%"],["SLA Compliance",data.sla,"%"],["Issues Assisted",data.issues,""],["Training Hours",data.trainingHours,"h"],["Final Score",data.finalScore,"%"]];return <><div className="pagehead"><div><span className="eyebrow">CREDLOCK SIWES</span><h1>SIWES Command Center</h1><p>Live operational overview from Google Sheets.</p></div><span className="source">{busy?"Refreshing…":"Connected"}</span></div><div className="identity"><div><small>INTERN</small><b>{fmt(data.intern)}</b></div><div><small>DEPARTMENT</small><b>{fmt(data.department)}</b></div><div><small>ORGANIZATION</small><b>{fmt(data.company)}</b></div><div><small>SUPERVISOR</small><b>{fmt(data.supervisor)}</b></div></div><div className="grid">{cards.map(([a,b,c])=><div className="card" key={a}><small>{a}</small><strong>{b==="—"?"—":`${fmt(b)}${c}`}</strong><span>Current record</span></div>)}</div><div className="panel"><div className="panelhead"><div><b>Connected data source</b><p>Authoritative SIWES records are served by the Google Apps Script API.</p></div><a href={SHEET} target="_blank" rel="noreferrer">Open Google Sheet <ExternalLink size={15}/></a></div></div></>}
function Students({rows,onRefresh}){const[q,setQ]=useState("");const list=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);return <><PageHead title="Students" sub="Manage SIWES student records and placements." action="Refresh" onAction={onRefresh}/><div className="toolbar"><Search size={17}/><input placeholder="Search students…" value={q} onChange={e=>setQ(e.target.value)}/></div><DataTable rows={list} keys={["SIWES ID","Full Name","Institution","Programme","Level","Status","Supervisor"]}/></>}
function Learning({rows}){return <><PageHead title="12-Week Learning Plan" sub="Structured training areas and expected outcomes."/><div className="plan-grid">{rows.map((r,i)=>{const a=Array.isArray(r)?r[0]:r.Week||i+1;const b=Array.isArray(r)?r[1]:r.Area;const c=Array.isArray(r)?r[2]:r.Activities;const d=Array.isArray(r)?r[3]:r.Outcome;return <article className="plan" key={i}><span>WEEK {a}</span><h3>{fmt(b)}</h3><p>{fmt(c)}</p><strong>Outcome</strong><p>{fmt(d)}</p></article>})}</div></>}
function Reports({data}){return <><PageHead title="Reports" sub="Operational reporting and source-data access."/><div className="report-grid"><div className="panel"><h3>SIWES performance</h3><p>Attendance, completion, support activity and assessment records are available from the connected workbook.</p><a href={SHEET} target="_blank" rel="noreferrer" className="primary link">Open reporting workbook</a></div><div className="panel"><h3>Backend status</h3><p>Google Apps Script is the live API layer. Refresh any module to retrieve current records.</p><span className="live"><i/> API configured</span></div></div></>}
function SettingsPage(){return <><PageHead title="Settings" sub="Portal configuration and administration resources."/><div className="panel settings"><div><small>DATA SOURCE</small><b>Google Sheets</b></div><div><small>API</small><b>Google Apps Script</b></div><div><small>SPREADSHEET</small><a href={SHEET} target="_blank" rel="noreferrer">Open connected sheet <ExternalLink size={15}/></a></div><div><small>SECURITY</small><b>Session-based portal access</b></div></div></>}
function PageHead({title,sub,action,onAction}){return <div className="pagehead"><div><span className="eyebrow">CREDLOCK SIWES</span><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="primary small" onClick={onAction}><RefreshCw size={16}/>{action}</button>}</div>}
function DataPage({title,rows,keys}){return <><PageHead title={title} sub="Live records from the SIWES workbook."/><DataTable rows={rows} keys={keys}/></>}
function DataTable({rows,keys}){return <div className="tablewrap"><table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{keys.map(k=><td key={k}>{fmt(Array.isArray(r)?r[k]:r[k])}</td>)}</tr>):<tr><td colSpan={keys.length} className="empty">No records returned.</td></tr>}</tbody></table></div>}
export default App;
